/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rubysurvey;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import static rubysurvey.Inicio.idEncuesta;
import static rubysurvey.Inicio.lista;
import static rubysurvey.Inicio.pregunta;
import static rubysurvey.Inicio.resMultiple;
import static rubysurvey.PreguntasSiNo.idEncuesta;

/**
 *
 * @author USER1
 */
public class RespuestaAbiertas extends javax.swing.JFrame {

    /**
     * Creates new form preguntasAbiertas
     */
    public static int idUsuarioEncuesta;
    public static String nombreEncuesta;
    public static int idEncuesta;
    public static int idPregunta;
    public static ArrayList<Integer> lista = new ArrayList<>();
    
    public static int screenCount;
    public RespuestaAbiertas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Pregunta Abierta?");

        jButton2.setText("Siguiente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel2)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton2)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        
        try{
            
                Connection con = Conection.getConexion();
                String query = "SELECT * FROM Preguntas where Tipo='"+jLabel2.getText()+"' ";
                PreparedStatement psmt = con.prepareStatement(query);
                ResultSet rs;
                rs = psmt.executeQuery();
                
                
                
                if(rs.next())
                {
                    int val = rs.getInt("idPreguntas");
                    idPregunta = val;
                    int val2 = rs.getInt("fkEncuesta");
                    idEncuesta = val2;
                    
                }
                
        } catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
        
        
        
        try{
            
                Connection con = Conection.getConexion();
                String query = "INSERT INTO RespuestaUsuarioAbierta(fkEncuesta,fkPreguntas,TextoAbierta) VALUES (?,?,?)";
                
                PreparedStatement psmt = con.prepareStatement(query);
                psmt.setInt(1, idEncuesta);
                psmt.setInt(2, idPregunta);
                psmt.setString(2, jTextArea1.getText());
                
                
                psmt.execute();
                System.out.println("sql success");
        } catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
        
        
        
        
        
        
        try{
        if(lista.get(screenCount-1) == 1)
        {
            RespuestaAbiertas newFrame= new RespuestaAbiertas();
            newFrame.setVisible(true);
            this.dispose();
            RespuestaAbiertas.lista = lista;
            RespuestaAbiertas.screenCount = RespuestaAbiertas.screenCount +1; 
            System.out.println(pregunta.get(screenCount-1));
            RespuestaAbiertas.jLabel2.setText(pregunta.get(screenCount-1));
        }
        else if(lista.get(screenCount-1) == 2)
        {
            RespuestaAbiertas newFrame= new RespuestaAbiertas();
            newFrame.setVisible(true);
            this.dispose();
            RespuestaSiNo.lista = lista;
            RespuestaSiNo.screenCount = RespuestaSiNo.screenCount +1; 
            RespuestaSiNo.preguntaP.setText(pregunta.get(screenCount-1));
        }
        else if(lista.get(screenCount-1) == 3)
        {
            
            RespuestaopcionMultiple newFrame= new RespuestaopcionMultiple();
            newFrame.setVisible(true);
            this.dispose();
            RespuestaopcionMultiple.lista = lista;
            RespuestaopcionMultiple.screenCount = RespuestaopcionMultiple.screenCount +1; 
            RespuestaopcionMultiple.jLabel4.setText(pregunta.get(screenCount-1));
            
            
            try{
            
                // se obtiene el id del tipo de pregunta para elegir siguiente pantalla
                Connection con = Conection.getConexion();
                String query = "SELECT idPreguntas FROM Preguntas where fkEncuesta='"+idEncuesta+"' ";
                PreparedStatement psmt = con.prepareStatement(query);
                ResultSet rs;
                rs = psmt.executeQuery();
                
                
                
                while(rs.next())
                {
                    int val = rs.getInt("idPreguntas");
                    String temps = Integer.toString(val);
                    resMultiple.add(temps);
                }
                
            } catch (SQLException ex){
                System.out.println(ex.getMessage());
            }
            
            RespuestaopcionMultiple.res1.setText(resMultiple.get(0));
            RespuestaopcionMultiple.res2.setText(resMultiple.get(1));
            RespuestaopcionMultiple.res3.setText(resMultiple.get(2));
            RespuestaopcionMultiple.res4.setText(resMultiple.get(3));
            
            
        }
        }
        catch (Exception e){
            Finalizar newFrame= new Finalizar();
            newFrame.setVisible(true);
            this.dispose();
        }
        
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RespuestaAbiertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RespuestaAbiertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RespuestaAbiertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RespuestaAbiertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RespuestaAbiertas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
