/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rubysurvey;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import static rubysurvey.Inicio.pregunta;
import static rubysurvey.Inicio.resMultiple;
import static rubysurvey.RespuestaopcionMultiple.idEncuesta;
import static rubysurvey.RespuestaopcionMultiple.lista;
import static rubysurvey.RespuestaopcionMultiple.screenCount;

/**
 *
 * @author USER1
 */
public class RespuestaSiNo extends javax.swing.JFrame {

    /**
     * Creates new form PreguntasSiNo
     */
    public static int idUsuarioEncuesta;
    public static String nombreEncuesta;
    public static int idEncuesta;
    public static int idPregunta;
    public static int idRespuestaOpcion;
    
    
    public static ArrayList<Integer> lista = new ArrayList<>();
    public static int screenCount;
    
    public RespuestaSiNo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        finalizar = new javax.swing.JButton();
        si = new javax.swing.JRadioButton();
        No = new javax.swing.JRadioButton();
        preguntaP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        finalizar.setText("Siguiente");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });

        si.setText("Si");
        si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siActionPerformed(evt);
            }
        });

        No.setText("No");
        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });

        preguntaP.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(finalizar)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(No)
                    .addComponent(si))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(preguntaP)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(preguntaP)
                .addGap(37, 37, 37)
                .addComponent(si)
                .addGap(18, 18, 18)
                .addComponent(No)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(finalizar)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
        // TODO add your handling code here:
         
        try{
        if(lista.get(screenCount-1) == 1)
        {
            RespuestaAbiertas newFrame= new RespuestaAbiertas();
            newFrame.setVisible(true);
            this.dispose();
            RespuestaAbiertas.lista = lista;
            RespuestaAbiertas.screenCount = RespuestaAbiertas.screenCount +1; 
            System.out.println(pregunta.get(screenCount-1));
            RespuestaAbiertas.jLabel2.setText(pregunta.get(screenCount-1));
        }
        else if(lista.get(screenCount-1) == 2)
        {
            RespuestaSiNo newFrame= new RespuestaSiNo();
            newFrame.setVisible(true);
            this.dispose();
            RespuestaSiNo.lista = lista;
            RespuestaSiNo.screenCount = RespuestaSiNo.screenCount +1; 
            RespuestaSiNo.preguntaP.setText(pregunta.get(screenCount-1));
        }
        else if(lista.get(screenCount-1) == 3)
        {
            
            RespuestaopcionMultiple newFrame= new RespuestaopcionMultiple();
            newFrame.setVisible(true);
            this.dispose();
            RespuestaopcionMultiple.lista = lista;
            RespuestaopcionMultiple.screenCount = RespuestaopcionMultiple.screenCount +1; 
            //RespuestaopcionMultiple.jLabel4.setText(pregunta.get(screenCount-1));
            
            
            try{
            
                // se obtiene el id del tipo de pregunta para elegir siguiente pantalla
                Connection con = Conection.getConexion();
                String query = "SELECT idPreguntas FROM Preguntas where fkEncuesta='"+idEncuesta+"' ";
                PreparedStatement psmt = con.prepareStatement(query);
                ResultSet rs;
                rs = psmt.executeQuery();
                
                
                
                while(rs.next())
                {
                    int val = rs.getInt("idPreguntas");
                    String temps = Integer.toString(val);
                    resMultiple.add(temps);
                }
                
            } catch (SQLException ex){
                System.out.println(ex.getMessage());
            }
            
            RespuestaopcionMultiple.res1.setText(resMultiple.get(0));
            RespuestaopcionMultiple.res2.setText(resMultiple.get(1));
            RespuestaopcionMultiple.res3.setText(resMultiple.get(2));
            RespuestaopcionMultiple.res4.setText(resMultiple.get(3));
            
            
        }
        }
        catch (Exception e){
            Finalizar newFrame= new Finalizar();
            newFrame.setVisible(true);
            this.dispose();
        }
        
        
    }//GEN-LAST:event_finalizarActionPerformed

    private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
        // TODO add your handling code here:
        
        try{
            
                Connection con = Conection.getConexion();
                String query = "SELECT * FROM Preguntas where Tipo='"+preguntaP.getText()+"' ";
                PreparedStatement psmt = con.prepareStatement(query);
                ResultSet rs;
                rs = psmt.executeQuery();
                
                
                
                if(rs.next())
                {
                    int val = rs.getInt("idPreguntas");
                    idPregunta = val;
                    int val2 = rs.getInt("fkEncuesta");
                    idEncuesta = val2;
                    
                }
                
        } catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
        
        try{
                
                String temp = "si";
                Connection con = Conection.getConexion();
                String query = "SELECT idRespuestaOpcion FROM RespuestaOpcion where TextoRespuesta='"+temp+"' ";
                PreparedStatement psmt = con.prepareStatement(query);
                ResultSet rs;
                rs = psmt.executeQuery();
                
                
                
                if(rs.next())
                {
                    
                    int val = rs.getInt("idRespuestaOpcion");
                    idRespuestaOpcion = val;
                    
                }
                
        } catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
        
        try{
            
                Connection con = Conection.getConexion();
                String query = "INSERT INTO RespuestaUsuarioOpcion(fkEncuesta,fkPreguntas,fkRespuestaOpcion) VALUES (?,?,?)";
                
                PreparedStatement psmt = con.prepareStatement(query);
                psmt.setInt(1, idEncuesta);
                psmt.setInt(2, idPregunta);
                psmt.setInt(2, idRespuestaOpcion);
                
                
                psmt.execute();
                System.out.println("sql success");
        } catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_siActionPerformed

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        // TODO add your handling code here:
        try{
            
                Connection con = Conection.getConexion();
                String query = "SELECT * FROM Preguntas where Tipo='"+preguntaP.getText()+"' ";
                PreparedStatement psmt = con.prepareStatement(query);
                ResultSet rs;
                rs = psmt.executeQuery();
                
                
                
                if(rs.next())
                {
                    int val = rs.getInt("idPreguntas");
                    idPregunta = val;
                    int val2 = rs.getInt("fkEncuesta");
                    idEncuesta = val2;
                    
                }
                
        } catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
        
        try{
                
                String temp = "no";
                Connection con = Conection.getConexion();
                String query = "SELECT idRespuestaOpcion FROM RespuestaOpcion where TextoRespuesta='"+temp+"' ";
                PreparedStatement psmt = con.prepareStatement(query);
                ResultSet rs;
                rs = psmt.executeQuery();
                
                
                
                if(rs.next())
                {
                    
                    int val = rs.getInt("idRespuestaOpcion");
                    idRespuestaOpcion = val;
                    
                }
                
        } catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
        
        try{
            
                Connection con = Conection.getConexion();
                String query = "INSERT INTO RespuestaUsuarioOpcion(fkEncuesta,fkPreguntas,fkRespuestaOpcion) VALUES (?,?,?)";
                
                PreparedStatement psmt = con.prepareStatement(query);
                psmt.setInt(1, idEncuesta);
                psmt.setInt(2, idPregunta);
                psmt.setInt(2, idRespuestaOpcion);
                
                
                psmt.execute();
                System.out.println("sql success");
        } catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_NoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RespuestaSiNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RespuestaSiNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RespuestaSiNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RespuestaSiNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RespuestaSiNo().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JRadioButton No;
    private javax.swing.JButton finalizar;
    public static javax.swing.JLabel preguntaP;
    public static javax.swing.JRadioButton si;
    // End of variables declaration//GEN-END:variables
}
